/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_Driver */

#ifndef _Included_jfprint_Driver
#define _Included_jfprint_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_Driver
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_Driver_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Driver
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfprint_Driver_getName
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Driver
 * Method:    getFullName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfprint_Driver_getFullName
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Driver
 * Method:    getDriverID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jfprint_Driver_getDriverID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
